### ISSUE TITLE
downloadReportWithHttpInfo returns an already closed InputStream

### ISSUE THREAD

**Issue by willoakley** [CyberSource/cybersource-rest-client-java#102]
When calling the ReportDownloadsApi::downloadReportWithHttpInfo() the returned InputStream from getData() has been closed and cannot be read. The client examples suggest the stream should be readable.

I believe the stream is being closed deliberately by `response.body().close()` [L1211](https://github.com/CyberSource/cybersource-rest-client-java/blob/4a86d78bfd0b71123f10137ebad3c625e2cc8fc4/src/main/java/Invokers/ApiClient.java#L1211) that was added to [v0.0.36](https://mvnrepository.com/artifact/com.cybersource/cybersource-rest-client-java/0.0.36) to fix issue #21. The ApiClient::deserialise() function returns the response stream as-is but it is then closed as the response.body(). The closing of the body stream likely wants to be only for non-stream response types that have already been deserialised.

**Comment by willoakley** [comment]
I see that pull request #98 should resolve this issue

**Comment by gnongsie** [comment]
This issue has been fixed and released as part of v0.0.40. 

@willoakley : Kindly confirm and close the ticket.

**Comment by willoakley** [comment]
The issue has been successfully resolved, thanks.
