### ISSUE TITLE
ApiClient logging/log level

### ISSUE THREAD

**Issue by rookmoose** [CyberSource/cybersource-rest-client-java#123]
Hi,
How is logging managed for the ApiClient? line 770: logger.info("HTTP Response Body :\n{}", data); is logging a very large JSON string and I'd like to be able to disable this.

Thanks

**Comment by gnongsie** [comment]
Hi @rookmoose , please refer to [Logging.md](https://github.com/CyberSource/cybersource-rest-client-java/blob/master/Logging.md) for detailed information about how to configure the logging framework.

**Comment by francisfree** [comment]
Hi @rookmoose  better solution

logging.level.com.cybersource.authsdk=off
logging.level.com.cybersource.logging=off
logging.level.Api=off
logging.level.Invokers=off
logging.level.Model=off
