### ISSUE TITLE
Getting java.lang.NumberFormatException in 0.0.55

### ISSUE THREAD

**Issue by Suryakanta26** [CyberSource/cybersource-rest-client-java#132]
Hi, 

While using **0.0.55** version to invoke **PayerAuthenticationApi.checkPayerAuthEnrollmentAsync()** api, I am getting error `java.lang.NumberFormatException: For input string: "MerchantACS"` . 

Here is the obfuscated enrollment response
`{
   "clientReferenceInformation":{
      ...
   },
   "consumerAuthenticationInformation":{
      ........
      **"acsOperatorID":"MerchantACS",**
      "specificationVersion":"2.1.0",
      ....
   },
   "id":"6938355855996032004951",
   .......
   "status":"AUTHENTICATION_SUCCESSFUL",
   "submitTimeUtc":"2023-09-04T13:53:05Z"
}`

Check the **acsOperatorID** attribute, it's coming as String, whereas in the corresponding Model class it is Integer.
https://github.com/CyberSource/cybersource-rest-client-java/blob/f4674b5846b99d616a734a49b706631fceae01e4/src/main/java/Model/RiskV1DecisionsPost201ResponseConsumerAuthenticationInformation.java#L150
This is causing NumberFormatException. Can anyone please look into this mismatch?

Note: I think this issue is started from **0.0.52**.

**Comment by DanielX66Z** [comment]
The same case in version 0.0.56

**Comment by gnongsie** [comment]
Hi @Suryakanta26 , this has been fixed and released in version 0.0.57.
Closing this issue based on that.
