### ISSUE TITLE
Issue with ApiClient.Java constructors

### ISSUE THREAD

**Issue by PeterSherk** [CyberSource/cybersource-rest-client-java#25]
The second constructor for ApiClient should call the default constructor. If you use the second constructor:

```
public ApiClient(MerchantConfig merchantConfig) {
	this.merchantConfig = merchantConfig;

}
```

you then error out because things like httpClient and json aren't being initialized (NullPointerExceptions).

**Comment by gnongsie** [comment]
Hi,

Thank you for bringing this to our attention.

This issue has been addressed in the latest version of the SDK. 
Kindly fetch the SDK from Maven **(v0.0.12)** and check again.
