### ISSUE TITLE
Async methods are not working since v0.0.16

### ISSUE THREAD

**Issue by Suryakanta26** [CyberSource/cybersource-rest-client-java#47]
Hi Cybersource Team, 

I am trying to use the Async version method (of cybersource-rest-client-java) for creating PaymentInstrumentToken.
Below is the code snippet, what I am trying.

`PaymentInstrumentApi paymentInstrumentApi = new PaymentInstrumentApi(apiClient);
			CreatePaymentInstrumentRequest createPaymentInstrumentRequest = new CreatePaymentInstrumentRequest();
			createPaymentInstrumentRequest = createRequest(createPaymentInstrumentRequest);

			paymentInstrumentApi.createPaymentInstrumentAsync(profileId, createPaymentInstrumentRequest,
					new ApiCallback<TmsV1InstrumentIdentifiersPaymentInstrumentsGet200ResponseEmbeddedPaymentInstruments>() {

						@Override
						public void onUploadProgress(long bytesWritten, long contentLength, boolean done) {
						}

						@Override
						public void onSuccess(
								TmsV1InstrumentIdentifiersPaymentInstrumentsGet200ResponseEmbeddedPaymentInstruments result,
								int statusCode, Map<String, List<String>> responseHeaders) {
							System.out.println("Response ID: " + result.getId());
							System.out.println("Bill To: " + result.getBillTo());
							System.out.println("Card: " + result.getCard());

							System.out.println("ResponseBody :" + apiClient.respBody);
							
						}

						@Override
						public void onFailure(ApiException e, int statusCode,
								Map<String, List<String>> responseHeaders) {

						}

						@Override
						public void onDownloadProgress(long bytesRead, long contentLength, boolean done) {
						}
			});`

But, I am getting **java.lang.UnsupportedOperationException**

`java.lang.UnsupportedOperationException: null
        at java.util.Collections$UnmodifiableCollection.add(Unknown Source) ~[?:1.8.0_192]
        at Api.PaymentInstrumentApi.createPaymentInstrumentCall(PaymentInstrumentApi.java:97) 
        at Api.PaymentInstrumentApi.createPaymentInstrumentValidateBeforeCall(PaymentInstrumentApi.java:126) 
        at Api.PaymentInstrumentApi.createPaymentInstrumentAsync(PaymentInstrumentApi.java:192) 
        at com.dummy.payment.transaction.service.impl.PaymentRequestServiceImpl.createPaymentInstrument(PaymentRequestServiceImpl.java:107)`

Can you please look into this?

**Note**: This issue was not present in v0.0.15, but present from v0.0.16 to latest v0.0.18-SNAPSHOT

Thank you.
Surya

*************** Update as on 18-02-2010 *************
After waiting for 12 days, it seems no one willing to fix this issue. So, I have spent some time to digging this issue. In ver. 3 of **OkHttpClient** has made **networkInterceptors()** to return an immutable list of interceptors, we need to find other option to add networkinterceptor.

**Comment by Suryakanta26** [comment]
Hi @gnongsie, I have provided the fix for **PayerAuthenticationApi** & **PaymentInstrumentApi** in my forked cybersource-rest-client-java [repository](https://github.com/Suryakanta26/cybersource-rest-client-java/commits/Fix-PaymentInstrumentApi-Async-Method). Can you please check these couple of commits?

- [Fix commit for PaymentInstrumentApi](https://github.com/Suryakanta26/cybersource-rest-client-java/commit/79924a8ecced9a0a7f904f0a8ffbcacb5f440695)
- [Fix commit for PayerAuthenticationApi](https://github.com/Suryakanta26/cybersource-rest-client-java/commit/0bd9bb02800c15e377b5dafe5b036fd1e87c7f39)

If you think it's ok, then pls include it for Feb 2020 release. Besides, we have to do similar changes for other APIs too.

Thanks
Surya

**Comment by gnongsie** [comment]
Hi @Suryakanta26 ,

Thank you for bringing this to our attention. 

I have evaluated your suggestion and added it to the February 2020 release. You can find the changes in the latest version (v0.0.18).

Regards,
@gnongsie

**Comment by Suryakanta26** [comment]
Many thanks @gnongsie.

**Comment by Suryakanta26** [comment]
Sorry for late to close this.
