### ISSUE TITLE
Unable to pass query params in KeyGenerationApi

### ISSUE THREAD

**Issue by sskolla01** [CyberSource/cybersource-rest-client-java#51]
As suggested in https://developer.cybersource.com/api/developer-guides/dita-flex/SAFlexibleToken/FlexMicroform/GetStarted.html

I need to make api call to https://testflex.cybersource.com/flex/v1/keys?format=JWT.

However generate KeyGenerationApi.generatePublicKeyCall is not accepting any query params. Please help me on that, thanks.

**Comment by gnongsie** [comment]
Hi,

This functionality was only recently added to the SDK. You can find this new query parameter available in v0.0.20.

Kindly update the version and try again.

Feel free to reach out to us if you continue to face any issues.

**Comment by sskolla01** [comment]
Thanks for the fix, it works now.
