### ISSUE TITLE
Call to generatePublicKey fails in new version

### ISSUE THREAD

**Issue by mathifonseca** [CyberSource/cybersource-rest-client-java#87]
When updating to `0.0.34`, a JSON serialization error started to happen when calling the `generatePublicKey` method.

```
java.lang.IllegalArgumentException: jdk.internal.ref.PhantomCleanable<?> declares multiple JSON fields named next
```

<img width="569" alt="logs" src="https://user-images.githubusercontent.com/4367808/136207792-b32a91b3-0f30-4bab-b501-056e5a841c63.png">

**Comment by ernesto-avila** [comment]
I'm facing the same issue after upgrading to the latest cybersource-rest-client-java version due to the log4j vulnerability

**Comment by ernesto-avila** [comment]
> When updating to `0.0.34`, a JSON serialization error started to happen when calling the `generatePublicKey` method.
> 
> ```
> java.lang.IllegalArgumentException: jdk.internal.ref.PhantomCleanable<?> declares multiple JSON fields named next
> ```
> 
> <img alt="logs" width="569" src="https://user-images.githubusercontent.com/4367808/136207792-b32a91b3-0f30-4bab-b501-056e5a841c63.png">

did you found the issue?

**Comment by mathifonseca** [comment]
@ernesto-avila not yet, I rolled back to the previous version and it worked for now :(
